FROM node:16
WORKDIR /client
COPY package.json ./
COPY package-lock.json ./
RUN npm install 
COPY . .
EXPOSE 3003
CMD ["npm", "start"]

# FROM node:16
# WORKDIR /client
# COPY package.json ./
# RUN npm install
# COPY . .
# CMD ["npm", "start"]